### ISSUE TITLE
Question: can errbase report automatically?

### ISSUE THREAD

**Issue by olimart** [ankane/errbase#6]
Wondering if `errbase` reports exceptions automatically (without manually calling `Errbase.report(e)`) like https://github.com/smartinez87/exception_notification does?

Thanks

**Comment by ankane** [comment]
Most (if not all) of the underlying error libraries should do this automatically or have a way to set this up, so it shouldn't be needed in Errbase.

**Comment by olimart** [comment]
Thanks
